config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'main#index' 
  get 'about', to: 'about#index'

  get 'registrations', to: 'registrations#index'
  post 'registrations/new', to: 'registrations#create'
  get 'registrations/new', to: 'registrations#new'
  get 'registrations/:id/edit', to: 'registrations#edit', as: 'edit_registration'
  get 'registrations/:id', to: 'registrations#show', as: 'show_registration'
  patch 'registrations/:id', to: 'registrations#update', as: 'update_registration'
  put 'registrations/:id', to: 'registrations#update'
  delete 'registrations/:id/delete', to: 'registrations#destroy', as: 'destroy_registration'
  get 'registrations/:id/delete', to: 'registrations#destroy'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'

  get 'projetos', to: 'projetos#index'
  post 'projetos/new', to: 'projetos#create'
  get 'projetos/new', to: 'projetos#new'
  get 'projetos/:id/edit', to: 'projetos#edit', as: 'edit_projeto'
  get 'projetos/:id', to: 'projetos#show', as: 'show_projeto'
  patch 'projetos/:id', to: 'projetos#update', as: 'update_projeto'
  put 'projetos/:id', to: 'projetos#update'
  delete 'projetos/:id/delete', to: 'projetos#destroy', as: 'destroy_projeto'
  get 'projetos/:id/delete', to: 'projetos#destroy'

  get 'eventos', to: 'eventos#index'
  post 'eventos/new', to: 'eventos#create'
  get 'eventos/new', to: 'eventos#new'
  get 'eventos/:id/edit', to: 'eventos#edit', as: 'edit_evento'
  get 'eventos/:id', to: 'eventos#show', as: 'show_evento'
  patch 'eventos/:id', to: 'eventos#update', as: 'update_evento'
  put 'eventos/:id', to: 'eventos#update'
  delete 'eventos/:id/delete', to: 'eventos#destroy', as: 'destroy_evento'
  get 'eventos/:id/delete', to: 'eventos#destroy'

  get 'usuarioprojetos', to: 'usuarioprojetos#index'
  post 'usuarioprojetos/new', to: 'usuarioprojetos#create'
  get 'usuarioprojetos/new', to: 'usuarioprojetos#new'
  get 'usuarioprojetos/:id/edit', to: 'usuarioprojetos#edit', as: 'edit_usuarioprojeto'
  get 'usuarioprojetos/:id', to: 'usuarioprojetos#show', as: 'show_usuarioprojeto'
  patch 'usuarioprojetos/:id', to: 'usuarioprojetos#update', as: 'update_usuarioprojeto'
  put 'usuarioprojetos/:id', to: 'usuarioprojetos#update'
  delete 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy', as: 'destroy_usuarioprojeto'
  get 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy'

  get 'arquivos', to: 'arquivos#index'
  post 'arquivos/new', to: 'arquivos#create'
  get 'arquivos/new', to: 'arquivos#new'
  get 'arquivos/:id/edit', to: 'arquivos#edit', as: 'edit_arquivo'
  get 'arquivos/:id', to: 'arquivos#show', as: 'show_arquivo'
  patch 'arquivos/:id', to: 'arquivos#update', as: 'update_arquivo'
  put 'arquivos/:id', to: 'arquivos#update'
  delete 'arquivos/:id/delete', to: 'arquivos#destroy', as: 'destroy_arquivo'
  get 'arquivos/:id/delete', to: 'arquivos#destroy'
end

app/models/projeto.rb
require 'bcrypt'
class Projeto < ActiveRecord::Base
	include BCrypt
	belongs_to :usuario
	has_many :projetos
	validates :nome, presence: true
	validates :numero, presence: true
	validates :data, presence: true
	validates :dataInicio, presence: true
	validates :dataFim, presence: false
	validates :usuario_id, presence: true
	validates :status, presence: false
	validates :area, presence: false
	validates :departamento, presence: false
	validates :avaliacaoComite, presence: false
	validates :avaliacaoDepex, presence: false
	validates :avaliacaoGeral, presence: false
	validates :areaTematica, presence: false
	validates :objetivo, presence: false
end

app/controllers/concerns/projetos_controller.rb
class ProjetosController < ApplicationController
	before_action :authorize, except: [:index, :show]
	before_action :set_usuarios, only: [:edit, :update, :new, :create]
	before_action :set_usuarioprojetos, only: [:show]
	before_action :set_eventos, only: [:show]
	before_action :autorize_prof, only: [:new, :create, :edit, :destroy]

	def index
		if params[:nomeProjeto]
			@projeto = Projeto.where("lower(nome) like lower(?)", "%#{params[:nomeProjeto]}%").order("nome, departamento, area")
		else
			@projeto = Projeto.all.order("nome, departamento, area")
		end
		@usuarioLogado = current_usuario
	end

	def show
		@projeto = Projeto.find(params[:id])
	end
	
	def new
		@projeto = Projeto.new
	end

	def create
		@projeto = Projeto.new(projeto_params)
		if @projeto.save
			redirect_to projetos_path
			flash[:notice] = "Projeto foi criado com sucesso"
		else
			render :new
		end
	end 

	def edit
		@projeto = Projeto.find(params[:id])
		@projeto.data = @projeto.data == nil ? '' : @projeto.data.strftime("%d/%m/%Y")
		@projeto.dataInicio = @projeto.dataInicio == nil ? '' : @projeto.dataInicio.strftime("%d/%m/%Y")
		@projeto.dataFim = @projeto.dataFim == nil ? '' : @projeto.dataFim.strftime("%d/%m/%Y")
		render :edit
	end

	def update
		@projeto = Projeto.find(params[:id])
		if @projeto.update(projeto_params)
			flash[:notice] = "Projeto atualizado"
			redirect_to projetos_path
		else
			flash.now[:error] = "Erro ao salvar!"
			render :edit
		end

	end

	def destroy
		@projeto = Projeto.find(params[:id])
		@projeto.destroy
		flash[:notice] = "Projeto deletado"
		redirect_to projetos_path
	end


	private
	
	def projeto_params
		params.require(:projeto).permit(:nome, :numero, :data, :dataInicio, :dataFim, :status, :area, :departamento, :avaliacaComite, :avaliacaoDexep, :avaliacaoGeral, :usuario_id, :objetivo, :areaTematica)
	end	

	def find_user
    	@user = Projeto.find(params[:id])
  	end

  	def set_usuarios
  		@usuarios = Usuario.where(tipoUsuario: "Professor")
  	end

  	def set_usuarioprojetos
  		@usuarioprojeto = UsuarioProjeto.all
  	end

  	def set_eventos
  		@eventos = Evento.all
  	end
  	
end

app/views/projetos/edit.html.erb
<h1>Editar projeto</h1>

<%= form_for @projeto, url: update_projeto_path do |form| %>
<div class="mb-3">
	<%= form.label "Nome" %>
	<%= form.text_field :nome, :required => true, class: "form-control", placeholder:"Digite o nome do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Número" %>
	<%= form.text_field :numero, :required => true, class: "form-control", placeholder:"Digite o número do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Responsável pelo projeto"%>
	<%= form.collection_select(:usuario_id, @usuarios, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Data projeto" %>
	<%= form.text_field :data, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Data início" %>
	<%= form.text_field :dataInicio, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Data fim" %>
	<%= form.text_field :dataFim, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Status" %>
	<%= form.select :status, (["Concluído", "Em desenvolvimento", "Cancelado"]), {include_blank: true}, class: "form-select" %>
</div>
<div class="mb-3">
	<%= form.label "Área" %>
	<%= form.text_field :area, class: "form-control" , placeholder:"Digite a área relacionada ao projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Departamento" %>
	<%= form.text_field :departamento, class: "form-control" , placeholder:"Digite o departamento relacionado ao projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Área temática" %>
	<%= form.text_field :areaTematica, class: "form-control" , placeholder:"Digite a área temática do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Objetivo" %>
	<%= form.text_area :objetivo, class: "form-text" , placeholder:"Digite o objetivo do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Avaliação comitê" %>
	<%= form.text_field :avaliacaoComite, class: "form-control" , placeholder:"Digite a avaliação do comitê" %>
</div>
<div class="mb-3">
	<%= form.label "Avaliação depex" %>
	<%= form.text_field :avaliacaoDepex, class: "form-control" , placeholder:"Digite a avaliação do depex" %>
</div>
<div class="mb-3">
	<%= form.submit "Salvar", class:"btn btn-primary" %>
</div>
<% end %>

app/views/projetos/index.html.erb
<div>
  <div class="row">
    <div class="col col-sm-2 p-2">
      <h1>Projetos</h1>
    </div>
    <% if @usuarioLogado != nil %>
      <div class="col col-sm-2 col p-2" id="novoProjeto">
        <%= link_to image_tag("add.png", height: 25) + " Novo projeto", projetos_new_path, class: "nav-link" %>
      </div>
      <div class="col col-sm-3 col p-2" id="novoEvento">
        <%= link_to image_tag("add.png", height: 25) + " Adicionar usuario ao projeto", usuarioprojetos_new_path, class: "nav-link" %>
      </div>
      <div class="col col-sm-3 col p-2" id="novoArquivo">
        <%= link_to image_tag("add.png", height: 25) + " Adicionar arquivo ao projeto", arquivos_new_path, class: "nav-link" %>
      </div>
    <% end %>
  </div>
</div>
<div>
  <div class="row">
    <div class="col col-sm-2 p-2 bg-light border">
      <strong>Nome</strong>
    </div>
    <div class="col col-sm-1 col p-2 bg-light border">
      <strong>Numero</strong>
    </div>
    <div class="col col-sm-1 col p-2 bg-light border">
      <strong>Data</strong>
    </div>
    <div class="col col-sm-2 col p-2 bg-light border">
      <strong>Status</strong>
    </div>
    <div class="col col-sm-2 col p-2 bg-light border">
      <strong>Área</strong>
    </div>
    <div class="col col-sm-2 col p-2 bg-light border">
      <strong>Departamento</strong>
    </div>
    <div class="col col-sm-2">
    </div>
  </div>
</div>

<div>
  <div class="row">
  	<% @projeto.each do |projeto| %>
	    <div class="col col-sm-2 p-2 bg-light border">
	      <%= projeto.nome %>
	    </div>
	    <div class="col col-sm-1 col p-2 bg-light border">
	      <td><%= projeto.numero %></td>
	    </div>
	    <div class="col col-sm-1 col p-2 bg-light border">
	      <td><%= projeto.data.strftime("%d/%m/%Y") %></td>
	    </div>
      <div class="col col-sm-2 col p-2 bg-light border">
        <td><%= projeto.status %></td>
      </div>
      <div class="col col-sm-2 col p-2 bg-light border">
        <td><%= projeto.area %></td>
      </div>
      <div class="col col-sm-2 col p-2 bg-light border">
        <td><%= projeto.departamento %></td>
      </div>
      <div class="col col-sm-2 col p-2 bg-light border">
        <div class="d-flex"> 
          <% if @usuarioLogado != nil %>	    
            <%= link_to image_tag("edit.png", height: 25), edit_projeto_path(projeto), class: "nav-link" %>
            <%= link_to image_tag("delete1.png", height: 25), destroy_projeto_path(projeto), :method => :delete, class: "nav-link" %>
          <% end %> 
    	    <%= link_to image_tag("view.png", height: 25), show_projeto_path(projeto), class: "nav-link" %>
        </div>
	    </div>
    <% end %>
  </div>
</div>

app/views/projetos/new.html.erb
<h1>Criação de projeto</h1>

<%= form_for @projeto, url: projetos_new_path do |form| %>
<% if @projeto.errors.any? %>
<div id="error_explanation">
	<div class="alert-error">
		O formulário contém <%= pluralize(@projeto.errors.count, "erro") %>.
	</div>
	<ul>
		<% @projeto.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="mb-3">
	<%= form.label "Nome" %>
	<%= form.text_field :nome, :required => true, class: "form-control", placeholder:"Digite o nome do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Número" %>
	<%= form.text_field :numero, :required => true, class: "form-control", placeholder:"Digite o número do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Responsável pelo projeto"%>
	<%= form.collection_select(:usuario_id, @usuarios, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Data projeto" %>
	<%= form.text_field :data, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Data início" %>
	<%= form.text_field :dataInicio, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Data fim" %>
	<%= form.text_field :dataFim, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Status" %>
	<%= form.select :status, (["Concluído", "Em desenvolvimento", "Cancelado"]), {include_blank: true}, class: "form-select" %>
</div>
<div class="mb-3">
	<%= form.label "Área" %>
	<%= form.text_field :area, class: "form-control" , placeholder:"Digite a área relacionada ao projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Departamento" %>
	<%= form.text_field :departamento, class: "form-control" , placeholder:"Digite o departamento relacionado ao projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Área temática" %>
	<%= form.text_field :areaTematica, class: "form-control" , placeholder:"Digite a área temática do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Objetivo" %>
	<%= form.text_area :objetivo, class: "form-text" , placeholder:"Digite o objetivo do projeto" %>
</div>
<div class="mb-3">
	<%= form.label "Avaliação comitê" %>
	<%= form.text_field :avaliacaoComite, class: "form-control" , placeholder:"Digite a avaliação do comitê" %>
</div>
<div class="mb-3">
	<%= form.label "Avaliação depex" %>
	<%= form.text_field :avaliacaoDepex, class: "form-control" , placeholder:"Digite a avaliação do depex" %>
</div>
<div class="mb-3">
	<%= form.submit "Salvar", class:"btn btn-primary" %>
</div>
<% end %>

app/views/projetos/show.html.erb
<div>
    <h3>Projeto</h3>
    <strong>Nome:</strong>
    <%= @projeto.nome %>
    <br>
    <strong>Numero:</strong>
    <%= @projeto.numero %>
    <br>
    <strong>Responsável pelo projeto:</strong>
    <%= @projeto.usuario.nome %>
    <br>
    <strong>Data projeto:</strong>
    <%= @projeto.data.strftime("%d/%m/%Y") %>
    <br>
    <strong>Data início:</strong>
    <%= @projeto.dataInicio == nil ? '' : @projeto.dataInicio.strftime("%d/%m/%Y") %>
    <br>
    <strong>Data fim:</strong>
    <%= @projeto.dataFim == nil ? '' : @projeto.dataFim.strftime("%d/%m/%Y") %>
    <br>
    <strong>Status:</strong>
    <%= @projeto.status %>
    <br>
    <strong>Área:</strong>
    <%= @projeto.area %>
    <br>
    <strong>Departamento:</strong>
    <%= @projeto.departamento %>
    <br>
    <strong>Área temática:</strong>
    <%= @projeto.areaTematica %>
    <br>
    <strong>Objetivo:</strong>
    <%= @projeto.objetivo %>
    <br>
    <strong>Avaliação comitê:</strong>
    <%= @projeto.avaliacaoComite %>
    <br>
    <strong>Avaliação depex:</strong>
    <%= @projeto.avaliacaoDepex %>
    <br>
    <strong>Avaliação geral:</strong>
    <%= @projeto.avaliacaoGeral %>
    <br>
  <div>
    <h3>Usuários relacionados</h3>
    <% @usuarioprojeto.each do |usuarioprojeto| %>
      <% if usuarioprojeto.projeto.id = @projeto.id %>
          <strong>Tipo usuario:</strong>
          <%= usuarioprojeto.tipoUsuario %>
          <br>
          <strong>Usuario:</strong>
          <%= usuarioprojeto.usuario.nome %>
      <% end %>    
    <% end %>
  </div>
  <div>
    <h3>Eventos do projeto</h3>
    <% @eventos.each do |evento| %>
      <% if evento.projeto.id = @projeto.id %>
        <strong>Título</strong>
        <%= evento.titulo %>
        <br>
        <strong>Descrição</strong>
        <%= evento.descricao %>
        <br>
        <strong>Data do evento</strong>
        <%= evento.data == nil ? '' : evento.data.strftime("%d/%m/%Y") %>
        <br>
      <% end %>
    <% end %>
  </div>
</div>