config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'main#index' 
  get 'about', to: 'about#index'

  get 'registrations', to: 'registrations#index'
  post 'registrations/new', to: 'registrations#create'
  get 'registrations/new', to: 'registrations#new'
  get 'registrations/:id/edit', to: 'registrations#edit', as: 'edit_registration'
  get 'registrations/:id', to: 'registrations#show', as: 'show_registration'
  patch 'registrations/:id', to: 'registrations#update', as: 'update_registration'
  put 'registrations/:id', to: 'registrations#update'
  delete 'registrations/:id/delete', to: 'registrations#destroy', as: 'destroy_registration'
  get 'registrations/:id/delete', to: 'registrations#destroy'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'

  get 'projetos', to: 'projetos#index'
  post 'projetos/new', to: 'projetos#create'
  get 'projetos/new', to: 'projetos#new'
  get 'projetos/:id/edit', to: 'projetos#edit', as: 'edit_projeto'
  get 'projetos/:id', to: 'projetos#show', as: 'show_projeto'
  patch 'projetos/:id', to: 'projetos#update', as: 'update_projeto'
  put 'projetos/:id', to: 'projetos#update'
  delete 'projetos/:id/delete', to: 'projetos#destroy', as: 'destroy_projeto'
  get 'projetos/:id/delete', to: 'projetos#destroy'

  get 'eventos', to: 'eventos#index'
  post 'eventos/new', to: 'eventos#create'
  get 'eventos/new', to: 'eventos#new'
  get 'eventos/:id/edit', to: 'eventos#edit', as: 'edit_evento'
  get 'eventos/:id', to: 'eventos#show', as: 'show_evento'
  patch 'eventos/:id', to: 'eventos#update', as: 'update_evento'
  put 'eventos/:id', to: 'eventos#update'
  delete 'eventos/:id/delete', to: 'eventos#destroy', as: 'destroy_evento'
  get 'eventos/:id/delete', to: 'eventos#destroy'

  get 'usuarioprojetos', to: 'usuarioprojetos#index'
  post 'usuarioprojetos/new', to: 'usuarioprojetos#create'
  get 'usuarioprojetos/new', to: 'usuarioprojetos#new'
  get 'usuarioprojetos/:id/edit', to: 'usuarioprojetos#edit', as: 'edit_usuarioprojeto'
  get 'usuarioprojetos/:id', to: 'usuarioprojetos#show', as: 'show_usuarioprojeto'
  patch 'usuarioprojetos/:id', to: 'usuarioprojetos#update', as: 'update_usuarioprojeto'
  put 'usuarioprojetos/:id', to: 'usuarioprojetos#update'
  delete 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy', as: 'destroy_usuarioprojeto'
  get 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy'

  get 'arquivos', to: 'arquivos#index'
  post 'arquivos/new', to: 'arquivos#create'
  get 'arquivos/new', to: 'arquivos#new'
  get 'arquivos/:id/edit', to: 'arquivos#edit', as: 'edit_arquivo'
  get 'arquivos/:id', to: 'arquivos#show', as: 'show_arquivo'
  patch 'arquivos/:id', to: 'arquivos#update', as: 'update_arquivo'
  put 'arquivos/:id', to: 'arquivos#update'
  delete 'arquivos/:id/delete', to: 'arquivos#destroy', as: 'destroy_arquivo'
  get 'arquivos/:id/delete', to: 'arquivos#destroy'
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= flash[:notice]%>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% elsif flash[:error]%>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= flash[:error]%>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% elsif flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= flash[:alert]%>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if logged_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to image_tag("logo.png", height: 25), root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sobre", about_path, class: "nav-link" %>
          </li>
          <li class="vr"></li>
          <li>
            <%= link_to "Novo projeto", projetos_new_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Projetos", projetos_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Novo evento", eventos_new_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Eventos", eventos_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Novo arquivo", arquivos_new_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Arquivos", arquivos_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Novo usuário", registrations_new_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Usuários", registrations_path, class: "nav-link" %>
          </li>
        </ul>
        <li>
          <%= form_tag(projetos_path, method: :get) do %>
            <%= text_field_tag 'nomeProjeto', nil, placeholder: 'Pesquisar o projeto' %>
            <%= submit_tag "Pesquisar", class: "btn btn-primary" %>
          <% end %>
        </li>
        <ul>
        </ul>
        <form class="d-flex">
        <%= link_to "Logout", sign_out_path, class:"btn btn-primary" %>
        </form>
      <% else %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to image_tag("logo.png", height: 25), root_path, class: "nav-link active" %>
        </li>
        <li>
          <%= link_to "Visualizar projetos", projetos_path, class: "nav-link" %>
        </li>
        <li>
          <%= form_tag(projetos_path, method: :get) do %>
            <%= text_field_tag 'nomeProjeto', nil, placeholder: 'Pesquisar o projeto' %>
            <%= submit_tag "Pesquisar", class: "btn btn-primary btn-full" %>
          <% end %>
        </li>
      </ul>
      <ul>
      </ul>
      <form class="d-flex align-items-end">
        <%= link_to "Login", sign_in_path, class:"btn btn-primary" %>
      </form>
      <% end %>
    </div>

  </div>
</nav>