config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'main#index' 
  get 'about', to: 'about#index'

  get 'registrations', to: 'registrations#index'
  post 'registrations/new', to: 'registrations#create'
  get 'registrations/new', to: 'registrations#new'
  get 'registrations/:id/edit', to: 'registrations#edit', as: 'edit_registration'
  get 'registrations/:id', to: 'registrations#show', as: 'show_registration'
  patch 'registrations/:id', to: 'registrations#update', as: 'update_registration'
  put 'registrations/:id', to: 'registrations#update'
  delete 'registrations/:id/delete', to: 'registrations#destroy', as: 'destroy_registration'
  get 'registrations/:id/delete', to: 'registrations#destroy'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'

  get 'projetos', to: 'projetos#index'
  post 'projetos/new', to: 'projetos#create'
  get 'projetos/new', to: 'projetos#new'
  get 'projetos/:id/edit', to: 'projetos#edit', as: 'edit_projeto'
  get 'projetos/:id', to: 'projetos#show', as: 'show_projeto'
  patch 'projetos/:id', to: 'projetos#update', as: 'update_projeto'
  put 'projetos/:id', to: 'projetos#update'
  delete 'projetos/:id/delete', to: 'projetos#destroy', as: 'destroy_projeto'
  get 'projetos/:id/delete', to: 'projetos#destroy'

  get 'eventos', to: 'eventos#index'
  post 'eventos/new', to: 'eventos#create'
  get 'eventos/new', to: 'eventos#new'
  get 'eventos/:id/edit', to: 'eventos#edit', as: 'edit_evento'
  get 'eventos/:id', to: 'eventos#show', as: 'show_evento'
  patch 'eventos/:id', to: 'eventos#update', as: 'update_evento'
  put 'eventos/:id', to: 'eventos#update'
  delete 'eventos/:id/delete', to: 'eventos#destroy', as: 'destroy_evento'
  get 'eventos/:id/delete', to: 'eventos#destroy'

  get 'usuarioprojetos', to: 'usuarioprojetos#index'
  post 'usuarioprojetos/new', to: 'usuarioprojetos#create'
  get 'usuarioprojetos/new', to: 'usuarioprojetos#new'
  get 'usuarioprojetos/:id/edit', to: 'usuarioprojetos#edit', as: 'edit_usuarioprojeto'
  get 'usuarioprojetos/:id', to: 'usuarioprojetos#show', as: 'show_usuarioprojeto'
  patch 'usuarioprojetos/:id', to: 'usuarioprojetos#update', as: 'update_usuarioprojeto'
  put 'usuarioprojetos/:id', to: 'usuarioprojetos#update'
  delete 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy', as: 'destroy_usuarioprojeto'
  get 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy'

  get 'arquivos', to: 'arquivos#index'
  post 'arquivos/new', to: 'arquivos#create'
  get 'arquivos/new', to: 'arquivos#new'
  get 'arquivos/:id/edit', to: 'arquivos#edit', as: 'edit_arquivo'
  get 'arquivos/:id', to: 'arquivos#show', as: 'show_arquivo'
  patch 'arquivos/:id', to: 'arquivos#update', as: 'update_arquivo'
  put 'arquivos/:id', to: 'arquivos#update'
  delete 'arquivos/:id/delete', to: 'arquivos#destroy', as: 'destroy_arquivo'
  get 'arquivos/:id/delete', to: 'arquivos#destroy'
end

app/models/evento.rb
class Evento < ApplicationRecord
	has_one_attached :image
	belongs_to :projeto
	validate :acceptable_image

	def acceptable_image
  		return unless image.attached?

  		unless image.byte_size <= 1.megabyte
    		errors.add(:image, "is too big")
  		end

  		acceptable_types = ["image/jpeg", "image/png"]
  		unless acceptable_types.include?(image.content_type)
    	errors.add("Apenas imagens JPEG ou PNG são aceitas")
  end
	end
end

app/controllers/concerns/eventos_controller.rb
class EventosController < ApplicationController
	before_action :authorize, except: [:show]
	before_action :set_projetos, only: [:edit, :update, :new, :create]
	
	def index
		@evento = Evento.all.order("data")
	end

	def show
		@evento = Evento.find(params[:id])
	end
	
	def new
		@evento = Evento.new
	end

	def create
		@evento = Evento.new(evento_params)
		if @evento.save
			redirect_to eventos_path
			flash[:notice] = "Evento foi criado com sucesso"
		else
			render :new
		end
	end 

	def edit
		@evento = Evento.find(params[:id])
		@evento.data = @evento.data.strftime("%d/%m/%Y")
		render :edit
	end

	def update
		@evento = Evento.find(params[:id])
		if @evento.update(evento_params)
			flash[:notice] = "Evento atualizado"
			redirect_to eventos_path
		else
			flash.now[:error] = "Erro ao salvar!"
			render :edit
		end

	end

	def destroy
		@evento = Evento.find(params[:id])
		@evento.destroy
		flash[:notice] = "Evento deletado"
		redirect_to eventos_path
	end


	private
	
	def evento_params
		params.require(:evento).permit(:descricao, :data, :projeto_id, :link, :titulo, :image)
	end	

	def find_user
    	@user = Evento.find(params[:id])
  	end

  	def set_projetos
  		@projetos = Projeto.all
  	end
end

app/views/eventos/edit.html.erb
<h1>Editar eventos</h1>

<%= form_for @evento, url: update_evento_path do |form| %>
<div class="mb-3">
	<%= form.label "Título" %>
	<%= form.text_field :titulo, class: "form-control", placeholder:"Título do evento" %>
</div>
<div class="mb-3">
	<%= form.label "Descrição" %>
	<%= form.text_field :descricao, :required => true, class: "form-text", placeholder:"Descrição do evento" %>
</div>
<div class="mb-3">
	<%= form.label "Data do evento" %>
	<%= form.text_field :data, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Projeto"%>
	<%= form.collection_select(:projeto_id, @projetos, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Link" %>
	<%= form.text_field :link, class: "form-control", placeholder:"Link" %>
</div>
<div class="mb-3">
	<%= form.label "Imagem" %>
	<%= form.file_field :image, class: "form-control", placeholder:"Inserir imagem do evento" %>
</div>
<div class="mb-3">
	<%= form.submit "Salvar", class:"btn btn-primary" %>
</div>
<% end %>

app/views/eventos/index.html.erb
<div>
  <div class="row">
    <div class="col col-sm-2 p-2">
      <h1>Eventos</h1>
    </div>
    <div class="col col-sm-2 col p-2">
      <%= link_to image_tag("add.png", height: 25) + " Novo evento", eventos_new_path, class: "nav-link" %>
    </div>
  </div>
</div>

<div>
  <div class="row">
    <div class="col col-sm-3 p-2 bg-light border">
      <strong>Título</strong>
    </div>
    <div class="col col-sm-3 p-2 bg-light border">
      <strong>Descrição</strong>
    </div>
    <div class="col col-sm-1 col p-2 bg-light border">
      <strong>Data</strong>
    </div>
    <div class="col col-sm-3 col p-2 bg-light border">
      <strong>Projeto</strong>
    </div>
    <div class="col col-sm-2">
      
    </div>
  </div>
</div>

<div>
  <div class="row">
  	<% @evento.each do |evento| %>
      <div class="col col-sm-3 p-2 bg-light border">
        <%= evento.titulo %>
      </div>
	    <div class="col col-sm-3 p-2 bg-light border">
	      <%= evento.descricao %>
	    </div>
	    <div class="col col-sm-1 col p-2 bg-light border">
	      <td><%= evento.data.strftime("%d/%m/%Y") %></td>
	    </div>
	    <div class="col col-sm-3 col p-2 bg-light border">
	      <td><%= evento.projeto.nome %></td>
	    </div>
	    <div class="col col-sm-2 col p-2 bg-light border">
        <div class="d-flex"> 
          <%= link_to image_tag("edit.png", height: 25), edit_evento_path(evento), class: "nav-link" %>
          <%= link_to image_tag("delete1.png", height: 25), destroy_evento_path(evento), :method => :delete, class: "nav-link" %>
  	    	<%= link_to image_tag("view.png", height: 25), show_evento_path(evento), class: "nav-link" %>
        </div>
	    </div>
    <% end %>
  </div>
</div>

app/views/eventos/new.html.erb
<h1>Criação de eventos</h1>

<%= form_for @evento, url: eventos_new_path do |form| %>
<% if @evento.errors.any? %>
<div id="error_explanation">
	<div class="alert-error">
		O formulário contém <%= pluralize(@evento.errors.count, "erro") %>.
	</div>
	<ul>
		<% @evento.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="mb-3">
	<%= form.label "Título" %>
	<%= form.text_field :titulo, class: "form-control", placeholder:"Título do evento" %>
</div>
<div class="mb-3">
	<%= form.label "Descrição" %>
	<%= form.text_area :descricao, :required => true, class: "form-text", placeholder:"Descrição do evento" %>
</div>
<div class="mb-3">
	<%= form.label "Data do evento" %>
	<%= form.text_field :data, ({"data-provide" => 'datepicker', "data-date-format" => "dd/mm/yyyy", class: "form-date",placeholder: "DD/MM/YYYY"}) %>
</div>
<div class="mb-3">
	<%= form.label "Projeto"%>
	<%= form.collection_select(:projeto_id, @projetos, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Link" %>
	<%= form.text_field :link, class: "form-control", placeholder:"Link" %>
</div>
<div class="mb-3">
	<%= form.label "Imagem" %>
	<%= form.file_field :image, class: "form-control", placeholder:"Inserir imagem do evento" %>
</div>
<div class="mb-3">
	<%= form.submit "Salvar", class:"btn btn-primary" %>
</div>
<% end %>

app/views/eventos/show.html.erb
<div>
  <p>
    <strong>Título:</strong>
    <%= @evento.titulo %>
  </p>
  <p>
    <strong>Descrição:</strong>
    <%= @evento.descricao %>
  </p>
  <p>
    <strong>Data:</strong>
    <%= @evento.data.strftime("%d/%m/%Y") %>
  </p>
  <p>
    <strong>Evento do projeto:</strong>
    <%= @evento.projeto.nome %>
  </p>
  <p>
    <strong>Link:</strong>
    <%= link_to @evento.link, "http://#{@evento.link}" %>
  </p>
  <p>
    <strong>Imagem:</strong>
    <%= image_tag @evento.image %>
  </p>
</div>