config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'main#index' 
  get 'about', to: 'about#index'

  get 'registrations', to: 'registrations#index'
  post 'registrations/new', to: 'registrations#create'
  get 'registrations/new', to: 'registrations#new'
  get 'registrations/:id/edit', to: 'registrations#edit', as: 'edit_registration'
  get 'registrations/:id', to: 'registrations#show', as: 'show_registration'
  patch 'registrations/:id', to: 'registrations#update', as: 'update_registration'
  put 'registrations/:id', to: 'registrations#update'
  delete 'registrations/:id/delete', to: 'registrations#destroy', as: 'destroy_registration'
  get 'registrations/:id/delete', to: 'registrations#destroy'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'

  get 'projetos', to: 'projetos#index'
  post 'projetos/new', to: 'projetos#create'
  get 'projetos/new', to: 'projetos#new'
  get 'projetos/:id/edit', to: 'projetos#edit', as: 'edit_projeto'
  get 'projetos/:id', to: 'projetos#show', as: 'show_projeto'
  patch 'projetos/:id', to: 'projetos#update', as: 'update_projeto'
  put 'projetos/:id', to: 'projetos#update'
  delete 'projetos/:id/delete', to: 'projetos#destroy', as: 'destroy_projeto'
  get 'projetos/:id/delete', to: 'projetos#destroy'

  get 'eventos', to: 'eventos#index'
  post 'eventos/new', to: 'eventos#create'
  get 'eventos/new', to: 'eventos#new'
  get 'eventos/:id/edit', to: 'eventos#edit', as: 'edit_evento'
  get 'eventos/:id', to: 'eventos#show', as: 'show_evento'
  patch 'eventos/:id', to: 'eventos#update', as: 'update_evento'
  put 'eventos/:id', to: 'eventos#update'
  delete 'eventos/:id/delete', to: 'eventos#destroy', as: 'destroy_evento'
  get 'eventos/:id/delete', to: 'eventos#destroy'

  get 'usuarioprojetos', to: 'usuarioprojetos#index'
  post 'usuarioprojetos/new', to: 'usuarioprojetos#create'
  get 'usuarioprojetos/new', to: 'usuarioprojetos#new'
  get 'usuarioprojetos/:id/edit', to: 'usuarioprojetos#edit', as: 'edit_usuarioprojeto'
  get 'usuarioprojetos/:id', to: 'usuarioprojetos#show', as: 'show_usuarioprojeto'
  patch 'usuarioprojetos/:id', to: 'usuarioprojetos#update', as: 'update_usuarioprojeto'
  put 'usuarioprojetos/:id', to: 'usuarioprojetos#update'
  delete 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy', as: 'destroy_usuarioprojeto'
  get 'usuarioprojetos/:id/delete', to: 'usuarioprojetos#destroy'

  get 'arquivos', to: 'arquivos#index'
  post 'arquivos/new', to: 'arquivos#create'
  get 'arquivos/new', to: 'arquivos#new'
  get 'arquivos/:id/edit', to: 'arquivos#edit', as: 'edit_arquivo'
  get 'arquivos/:id', to: 'arquivos#show', as: 'show_arquivo'
  patch 'arquivos/:id', to: 'arquivos#update', as: 'update_arquivo'
  put 'arquivos/:id', to: 'arquivos#update'
  delete 'arquivos/:id/delete', to: 'arquivos#destroy', as: 'destroy_arquivo'
  get 'arquivos/:id/delete', to: 'arquivos#destroy'
end

app/models/usuario_projeto.rb
class UsuarioProjeto < ApplicationRecord
  belongs_to :usuario
  belongs_to :projeto
end

app/controllers/concerns/usuarioprojetos_controller.rb
class UsuarioprojetosController < ApplicationController
	before_action :authorize
	before_action :set_usuarios, only: [:edit, :update, :new, :create]
	before_action :set_projetos, only: [:edit, :update, :new, :create]
	
	def index
		@usuarioprojeto = UsuarioProjeto.all
	end

	def show
		@usuarioprojeto = UsuarioProjeto.find(params[:id])
	end
	
	def new
		@usuarioprojeto = UsuarioProjeto.new
	end

	def create
		@usuarioprojeto = UsuarioProjeto.new(usuarioprojeto_params)
		if @usuarioprojeto.save
			redirect_to projetos_path
			flash[:notice] = "Usuario adicionado ao projeto"
		else
			render :new
		end
	end 

	def edit
		@usuarioprojeto = UsuarioProjeto.find(params[:id])
		render :edit
	end

	def update
		@usuarioprojeto = UsuarioProjeto.find(params[:id])
		if @usuarioprojeto.update(projeto_params)
			flash[:notice] = "Projeto atualizado"
			redirect_to usuarioprojetos_path
		else
			flash.now[:error] = "Erro ao salvar!"
			render :edit
		end

	end

	def destroy
		@usuarioprojeto = UsuarioProjeto.find(params[:id])
		@usuarioprojeto.destroy
		flash[:notice] = "Projeto deletado"
		redirect_to projetos_path
	end


	private
	
	def usuarioprojeto_params
		params.require(:usuario_projeto).permit(:usuario_id, :projeto_id, :cargaHoraria, :tipoUsuario)
	end	

	def set_usuarios
  		@usuarios = Usuario.all
  	end

  	def set_projetos
  		@projetos = Projeto.all
  	end

end

app/views/usuarioprojetos/edit.html.erb
<%= form_for @usuarioprojeto, url: update_usuarioprojeto_path do |form| %>

<div class="mb-3">
	<%= form.label "Usuário" %>
	<%= form.collection_select(:usuario_id, @usuarios, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Tipo de usuário" %>
	<%= form.select :tipoUsuario, (["Coordenador", "Vice-coordenador", "Aluno", "Equipe executora"]), {include_blank: true}, class: "form-select" %>
</div>
<div class="mb-3">
	<%= form.label "Projeto" %>
	<%= form.collection_select(:projeto_id, @projetos, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Carga horaria" %>
	<%= form.text_field :cargaHoraria, class: "form-control" , placeholder:"Digite a carga horária" %>
</div>
<div class="mb-3">
	<%= form.submit "Salvar", class:"btn btn-primary" %>
</div>
<% end %>

app/views/usuarioprojetos/index.html.erb
<div>
  <div class="row">
    <div class="col col-sm-6 p-2">
      <h1>Projeto-Usuário</h1>
    </div>
  </div>
</div>
<div>
  <div class="row">
    <div class="col col-sm-2 p-2 bg-light border">
      <strong>Usuário</strong>
    </div>
    <div class="col col-sm-2 col p-2 bg-light border">
      <strong>Tipo de usuário</strong>
    </div>
    <div class="col col-sm-3 col p-2 bg-light border">
      <strong>Projeto</strong>
    </div>
    <div class="col col-sm-2 col p-2 bg-light border">
      <strong>Carga horária</strong>
    </div>
    <div class="col col-sm-1 col p-2 bg-light border">
      <strong>Editar</strong>
    </div>
    <div class="col col-sm-1 col p-2 bg-light border">
      <strong>Deletar</strong>
    </div>
    <div class="col col-sm-1 col p-2 bg-light border">
      <strong>Visualizar</strong>
    </div>
  </div>
</div>

<div>
  <div class="row">
  	<% @usuarioprojeto.each do |usuarioprojeto| %>
	    <div class="col col-sm-2 p-2 bg-light border">
	      <%= usuarioprojeto.usuario.nome %>
	    </div>
	    <div class="col col-sm-2 col p-2 bg-light border">
	      <td><%= usuarioprojeto.tipoUsuario %></td>
	    </div>
	    <div class="col col-sm-3 col p-2 bg-light border">
	      <td><%= usuarioprojeto.projeto.nome %></td>
	    </div>
      <div class="col col-sm-2 col p-2 bg-light border">
        <td><%= usuarioprojeto.cargaHoraria %></td>
      </div>
	    <div class="col col-sm-1 col p-2 bg-light border">
        <%= link_to image_tag("edit.jpg", height: 25), edit_usuarioprojeto_path(usuarioprojeto), class: "nav-link" %>
	    </div>
	    <div class="col col-sm-1 col p-2 bg-light border">
        <%= link_to image_tag("delete.png", height: 25), destroy_usuarioprojeto_path(usuarioprojeto), :method => :delete %>
	    </div>
	    <div class="col col-sm-1 col p-2 bg-light border">
	    	<%= link_to image_tag("view.png", height: 25), show_usuarioprojeto_path(usuarioprojeto), class: "nav-link" %>
	    </div>
    <% end %>
  </div>
</div>

app/views/usuarioprojetos/new.html.erb
<h1>Adicionar usuários ao projeto</h1>

<%= form_for @usuarioprojeto, url: usuarioprojetos_new_path do |form| %>
<% if @usuarioprojeto.errors.any? %>
<div id="error_explanation">
	<div class="alert-error">
		O formulário contém <%= pluralize(@usuarioprojeto.errors.count, "erro") %>.
	</div>
	<ul>
		<% @usuarioprojeto.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="mb-3">
	<%= form.label "Usuário" %>
	<%= form.collection_select(:usuario_id, @usuarios, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Tipo de usuário" %>
	<%= form.select :tipoUsuario, (["Coordenador", "Vice-coordenador", "Aluno", "Equipe executora"]), {include_blank: true}, class: "form-select" %>
</div>
<div class="mb-3">
	<%= form.label "Projeto" %>
	<%= form.collection_select(:projeto_id, @projetos, :id, :nome, {include_blank: true}, class: "form-select") %>
</div>
<div class="mb-3">
	<%= form.label "Carga horaria" %>
	<%= form.text_field :cargaHoraria, class: "form-control" , placeholder:"Digite a carga horária" %>
</div>
<div class="mb-3">
	<%= form.submit "Salvar", class:"btn btn-primary" %>
</div>
<% end %>

app/views/usuarioprojetos/show.html.erb
<div>
  <p>
    <strong>Usuario:</strong>
    <%= @usuarioprojeto.usuario.nome %>
  </p>
  <p>
    <strong>Tipo de usuário:</strong>
    <%= @usuarioprojeto.tipoUsuario %>
  </p>
  <p>
    <strong>Projeto:</strong>
    <%= @usuarioprojeto.projeto.nome %>
  </p>
  <p>
    <strong>Carga horária:</strong>
    <%= @usuarioprojeto.cargaHoraria %>
  </p>
</div>